// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"server/internal/core/server"
	"server/internal/module/system/api"
	"server/internal/router"
)

// Injectors from wire.go:

func InitApp() (*server.HTTPServer, error) {
	systemApi := api.NewSystemApi()
	engine := router.NewRouter(systemApi)
	httpServer := server.NewHTTPServer(engine)
	return httpServer, nil
}
